### ISSUE TITLE
Add docstrings and comments

### ISSUE THREAD

**Issue by M4dhav** [notnotrachit/GitGoing#17]
**Description**:  
The current codebase lacks sufficient docstrings and comments, which makes it difficult for other developers (and future maintainers) to understand the purpose of various functions, classes, and complex logic. Adding comprehensive docstrings and inline comments will improve code clarity and maintainability.

#### Why It's Necessary:
- **Code Clarity**: Docstrings provide clear explanations of the functionality of functions, methods, and classes, making the code easier to understand for anyone working on it in the future.
- **Maintainability**: Well-commented code is easier to maintain, extend, and debug, especially for larger projects or when handed over to another developer.
- **Best Practices**: Adhering to best practices in documentation ensures consistency and professionalism in the codebase.

#### Action Steps:
1. Add descriptive docstrings to all functions, methods, and classes, following the format:
   - Brief description of the function/class.
   - Explanation of input parameters and expected types.
   - Description of the return value and its type.
   - Any exceptions or errors the function may raise.
2. Add inline comments for complex or non-obvious sections of code to explain why certain logic is implemented.
3. Ensure that the comments are up-to-date with the current implementation and remove any outdated or redundant comments.
4. Review the code for any areas where additional clarification would be beneficial, and add comments accordingly.
5. Test and run the application to ensure no impact on performance or functionality due to the added documentation.

**Comment by Mandy-cyber** [comment]
Could i take on this issue for `hacktoberfest`?

**Comment by notnotrachit** [comment]
Ya sure

**Comment by Mandy-cyber** [comment]
Thanks! I also have another PR out now 😄
