### ISSUE TITLE
Add requirements file

### ISSUE THREAD

**Issue by M4dhav** [notnotrachit/GitGoing#7]
Currently the repo does not have a requirements.txt which facilitates easy developmental setup.
Create and add an appropriate requirements.txt

**Comment by M4dhav** [comment]
Hey @notnotrachit I want to work on this issue

**Comment by notnotrachit** [comment]
Sure, go ahead

**Comment by M4dhav** [comment]
Made changes in #18

**Comment by shubh-3011** [comment]
made changes in #19
